### ISSUE TITLE
Question: How could I build and debug the extension within VSCODE's F5 mode?

### ISSUE THREAD

**Issue by noisnemid** [svaberg/SWMF-grammar#2]
I tried to run the source code in this way, but the debug mission report errors and exit.

```
git clone git@github.com:svaberg/SWMF-grammar.git --depth=1
cd SWMF-gramma
npm install
npm run compile
code .
```

PRESS \<F5\> and select 'Node.js'

error information:
```
C:\Program Files\nodejs\node.exe --inspect-brk=36597 out\extension.js 
Debugger listening on ws://127.0.0.1:36597/e168a396-2f2b-4c6a-83cf-0a322d16ee18
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the dError: Cannot find module 'vscode'
Require stack:
- c:\Users\***\Desktop\***\SWMF-grammar\out\extension.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (***\SWMF-grammar\src\extension.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:953:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
ebugger to disconnect...
```

environment information
```
os=windows 10 ,10.0.17763.973
vscode version = 1.41.1
node.js version = 12.13.0
```

**Comment by svaberg** [comment]
Hi noisnemid,

Thanks for noticing this! I have done a bit of googling and I am pretty sure that this is caused by Visual Studio Code now using `vscode-test` as a dependency instead of `vscode`, [which is  described on their home pages.](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode)

After fixing this issue I will update the repository and maybe create a new release.

Cheers,
Dag

**Comment by svaberg** [comment]
I think I have fixed this now - would you try it again on your side?

**Comment by noisnemid** [comment]
It's now running well in \<F5\> mode of visual studio code.
Thank you so much for your awesome works!!!
